# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/sm7225-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a42xq,$(TARGET_DEVICE)),)

endif
